key: ViT_MAE
fix: True
ckpt_path: /scratch/huangjiangyong/.cache/torch/hub/checkpoints/mae_pretrain_vit_base.pth
image_size: ${model.image_size}
patch_size: 16
reduction: [4, 8, 16, 32]
hidden_dim: [768, 768, 768, 768]
extract_layer: [2, 5, 8, 11]
