key: affordance

dataset:
  key: ADEAffordanceDataset
  info:
    subsets: [train, val, test]
    index_dir: /scratch/generalvision/ADE-Affordance
    img_dir: /scratch/generalvision/ADE20k/images/training
    seg_dir: /scratch/generalvision/ADE20k/annotations/training

decoder:
  key: DenseType
  params:
    image_size: ${model.image_size}
    input_dim_list: ${backbone.hidden_dim}
    hidden_dim: ${model.hidden_dim}
    dropout: 0.1
    num_classes: ${task.num_classes}

num_classes: 9
num_epochs: 50
loss: CrossEntropyLossWithIgnore

metrics: EvalSeg

visualize: VisSeg
