key: bongard

dataset:
  key: BongardHOIDataset
  info:
    subsets: [train, val, test]
    img_dir: /scratch/generalvision/bongard-hoi/images
    anno_dir: /scratch/generalvision/bongard-hoi/annos

decoder:
  key: LabelType
  params:
    image_size: ${model.image_size}
    grid_feature_ratio: ${backbone.grid_feature_ratio}
    reduction: ${backbone.reduction}
    input_dim_list: ${backbone.hidden_dim}
    hidden_dim: ${model.hidden_dim}
    transformer:
      num_layers: 6
      hidden_dim: ${task.decoder.params.hidden_dim}
      nheads: 8
      dropout: 0.1
    positional_embedding:
      type: sine
      hidden_dim: ${task.decoder.params.transformer.hidden_dim}
    num_classes: 2

num_epochs: 30
train_batch_size: 32
train_num_workers: 8
train_val_interval: 1
num_val_samples: 10000
eval_batch_size: 32
eval_num_workers: 8

loss: BongardLoss

metrics: EvalBongard

visualize: VisBongard
