key: camera_relocalization

dataset:
  key: CameraPoseDataset
  info:
    dataset: cambridgelandmarks
    cambridgelandmarks:
      subsets: [train, test]
      dataset_dir: /scratch/generalvision/CambridgeLandmarks
      scene: KingsCollege
      all_scenes: ['KingsCollege', 'OldHospital', 'ShopFacade', 'StMarysChurch']
    sevenscenes:
      subsets: [train, test]
      dataset_dir: /scratch/generalvision/7scenes
      scene: heads
      all_scenes: ['chess', 'fire', 'heads', 'office', 'pumpkin', 'redkitchen', 'stairs']

decoder:
  key: LabelType
  params:
    image_size: ${model.image_size}
    grid_feature_ratio: ${backbone.grid_feature_ratio}
    reduction: ${backbone.reduction}
    input_dim_list: ${backbone.hidden_dim}
    hidden_dim: ${model.hidden_dim}
    transformer:
      num_layers: 2
      hidden_dim: ${task.decoder.params.hidden_dim}
      nheads: 8
      dropout: 0.1
    positional_embedding:
      type: sine
      hidden_dim: ${task.decoder.params.transformer.hidden_dim}
    num_classes: 7

num_epochs: 200
loss: CameraRelocalizationLoss

metrics: EvalCameraRelocalization

visualize: VisCameraRelocalization