key: common_sense

dataset:
  key: VCRDataset
  info:
    subsets: [train, val]
    img_dir: /scratch/generalvision/vcr/vcr1images
    anno_dir: /scratch/generalvision/vcr

decoder:
  key: LabelType
  params:
    image_size: ${model.image_size}
    grid_feature_ratio: ${backbone.grid_feature_ratio}
    reduction: ${backbone.reduction}
    input_dim_list: ${backbone.hidden_dim}
    hidden_dim: ${model.hidden_dim}
    transformer:
      num_layers: 6
      hidden_dim: ${task.decoder.params.hidden_dim}
      nheads: 8
      dropout: 0.1
    positional_embedding:
      type: sine
      hidden_dim: ${task.decoder.params.transformer.hidden_dim}
    num_classes: 1

num_epochs: 20
train_batch_size: 128
train_num_workers: 20
train_val_interval: 1
num_val_samples: 15000
eval_batch_size: 100
eval_num_workers: 20

loss: CrossEntropyLoss

metrics: EvalVCR

visualize: VisVCR
