dataset:
  key: NYUv2Dataset
  info:
    subsets: [train, test]
    train_img_dir: /scratch/generalvision/NYUv2/sync
    test_img_dir: /scratch/generalvision/NYUv2/labelled
    train_index: /scratch/generalvision/NYUv2/sync/index_train.txt
    test_index: /scratch/generalvision/NYUv2/sync/index_test.txt

decoder:
  key: DenseType
  params:
    image_size: ${model.image_size}
    input_dim_list: ${backbone.hidden_dim}
    hidden_dim: ${model.hidden_dim}
    dropout: 0.1
    num_classes: 1

num_epochs: 100
loss: DepthLoss

metrics: EvalDepth

visualize: VisDepth
