key: navigation

dataset:
  info:
    mattersim_build_dir: /home/wllmzhu/github/Matterport3DSimulator/build     #path to locally compiled MatterSim package
    matterport_data_dir: /home/wllmzhu/data/matterport_data_new/v1/scans                   #path to downloaded Matterport3D dataset
    connectivity_dir: /home/wllmzhu/github/Recurrent-VLN-BERT/connectivity    #path to connectivity file
    img_feature_dir: /home/wllmzhu/data/r2r_img_features                      #path to the output directory for computed img features
    backbone_config_dir: /home/wllmzhu/github/G-VUE/configs/backbone
    prevalent_aug_path: None
    
    v_backbone_candidates: ['ViT_CLIP_16']
    candidate_configs:
      ResNet_ImageNet:
        key: ViT_CLIP_16
        fix: True



# dataset:
#   key: ADE20kDataset
#   info:
#     subsets: [train, val]
#     index_dir: /scratch/generalvision/ADE20k
#     img_dir: /scratch/generalvision/ADE20k/images
#     anno_dir: /scratch/generalvision/ADE20k/annotations

# decoder:
#   key: DenseType
#   params:
#     image_size: ${model.image_size}
#     input_dim_list: ${backbone.hidden_dim}
#     hidden_dim: ${model.hidden_dim}
#     dropout: 0.1
#     num_classes: ${task.num_classes}

# num_classes: 151
# num_epochs: 50
# loss: CrossEntropyLossWithIgnore

# metrics: EvalSeg

# visualize: VisSeg
