dataset:
  key: RefCOCODataset
  info:
    img_dir: /scratch/generalvision/mscoco/images/train2014
    anno_dir: /scratch/generalvision/refexp/annos/refcoco

decoder:
  key: LabelType
  params:
    reduction: ${backbone.reduction}
    input_dim_list: ${backbone.hidden_dim}
    hidden_dim: ${model.hidden_dim}
    transformer_encoder:
      num_layers: 6
      hidden_dim: ${task.decoder.params.hidden_dim}
      nheads: 8
      dropout: 0.1
    positional_embedding:
      type: sine
      hidden_dim: ${task.decoder.params.transformer_encoder.hidden_dim}
    num_classes: 4

loss:
  key: BboxLoss

metrics:
  key: EvalBbox

visualize: VisBbox
