key: phrase_grounding

dataset:
  key: RefCOCODataset
  info:
    subsets: [train, val, testA, testB]
    img_dir: /scratch/generalvision/mscoco/images/train2014
    anno_dir: /scratch/generalvision/refexp/annos/refcoco

decoder:
  key: LabelType
  params:
    image_size: ${model.image_size}
    reduction: ${backbone.reduction}
    input_dim_list: ${backbone.hidden_dim}
    hidden_dim: ${model.hidden_dim}
    transformer:
      num_layers: 6
      hidden_dim: ${task.decoder.params.hidden_dim}
      nheads: 8
      dropout: 0.1
    positional_embedding:
      type: sine
      hidden_dim: ${task.decoder.params.transformer.hidden_dim}
    num_classes: 4

num_epochs: 50
loss: BboxLoss

metrics: EvalBbox

visualize: VisBbox
