dataset:
  key: RefCOCODataset
  info:
    img_dir: /scratch/generalvision/mscoco/images/train2014
    anno_dir: /scratch/generalvision/refexp/annos/refcoco

decoder:
  key: QueryType
  params:
    input_dim_list: [2048]
    hidden_dim: null
    transformer_encoder:
      num_layers: 6
      hidden_dim: null
      nheads: null
      dropout: null
    transformer_decoder:
      num_layers: 6
      hidden_dim: null
      nheads: null
      dropout: null
    positional_embedding:
      type: sine
      hidden_dim: ${decoder.params.transformer_encoder.hidden_dim}
    num_queries: 100
