dataset:
  key: ADE20kDataset
  info:
    subsets: [train, val]
    top_dir: /mnt/huangjiangyong
    index_file: /mnt/huangjiangyong/ADE20K_2021_17_01/index_ade20k.pkl
    class_dict: /mnt/huangjiangyong/ADE20K_2021_17_01/class_index.txt

decoder:
  key: DenseType
  params:
    image_size: ${model.image_size}
    input_dim_list: ${backbone.hidden_dim}
    hidden_dim: ${model.hidden_dim}
    dropout: 0.1
    num_classes: 150

num_epochs: 50
loss: CrossEntropyLoss

metrics: EvalMask

visualize: VisMask
