dataset:
  key: null
  info:
    subsets: [train, val]
    top_dir: /home/wllmzhu/data/ade20k
    index_file: /home/wllmzhu/data/ade20k/ADE20K_2021_17_01/index_ade20k.pkl

decoder:
  key: DenseType
  params:
    image_size: ${model.image_size}
    input_dim_list: ${backbone.hidden_dim}
    hidden_dim: ${model.hidden_dim}
    dropout: 0.1
    num_classes: 150

num_epochs: 100
loss: CrossEntropyLoss

metrics: EvalMask

visualize: VisMask
