dataset:
  key: ADE20kDataset
  info:
    subsets: [train, val]
    index_dir: /home/wllmzhu/data/mit/ADEChallengeData2016/
    img_dir: /home/wllmzhu/data/mit/ADEChallengeData2016/images
    anno_dir: /home/wllmzhu/data/mit/ADEChallengeData2016/annotations

decoder:
  key: DenseType
  params:
    image_size: ${model.image_size}
    input_dim_list: ${backbone.hidden_dim}
    hidden_dim: ${model.hidden_dim}
    dropout: 0.1
    num_classes: 150

num_epochs: 50
loss: CrossEntropyLoss

metrics: EvalMask

visualize: VisMask
