key: vl_retrieval

dataset:
  key: Flickr30kDataset
  info:
    subsets: [train, val, test]
    anno_dir: /scratch/generalvision/flickr30k

decoder:
  embed_dim: 1024

num_epochs: 100
loss: ContrastiveLoss

text_batch_size: 1000
metrics: EvalRetrieval

visualize: VisRetrieval
