key: vl_retrieval

dataset:
  key: Flickr30kDataset
  info:
    subsets: [train, val, test]
    anno_dir: /scratch/generalvision/flickr30k

decoder:
  embed_dim: 1024

num_epochs: 50
train_batch_size: 256
train_num_workers: 20
train_val_interval: 10
num_val_samples: 500
eval_batch_size: 1
eval_num_workers: 0

loss: ContrastiveLoss
metrics: EvalRetrieval
text_batch_size: 1000
visualize: VisRetrieval
