dataset:
  key: GQADataset
  info:
    img_dir: /scratch/generalvision/GQA/images
    anno_dir: /scratch/generalvision/GQA/questions

decoder:
  key: LabelType
  params:
    image_size: ${model.image_size}
    reduction: ${backbone.reduction}
    input_dim_list: ${backbone.hidden_dim}
    hidden_dim: ${model.hidden_dim}
    transformer_encoder:
      num_layers: 6
      hidden_dim: ${task.decoder.params.hidden_dim}
      nheads: 8
      dropout: 0.1
    positional_embedding:
      type: sine
      hidden_dim: ${task.decoder.params.transformer_encoder.hidden_dim}
    num_classes: 1843

loss:
  key: CrossEntropyLoss
<<<<<<< HEAD
  params:
    num_classes: ${decoder.params.num_classes}
=======

metrics:
  key: EvalQA

visualize: VisQA
>>>>>>> dev
