dataset:
  key: GQADataset
  info:
    name: GQA
    img_dir: /scratch/generalvision/GQA/images
    anno_dir: /scratch/generalvision/GQA/questions

decoder:
  key: LabelType
  params:
    input_dim_list: [2048]
    hidden_dim: 256
    transformer_encoder:
      num_layers: 6
      hidden_dim: ${decoder.params.hidden_dim}
      nheads: 8
      dropout: 0.1
    positional_embedding:
      type: sine
      hidden_dim: ${decoder.params.transformer_encoder.hidden_dim}
    num_classes: 1800

loss:
  key: CrossEntropyLoss
  params:
    num_classes: ${decoder.params.num_classes}
